"""create_job_postings_table

Revision ID: c38ab889b22a
Revises: fe098cc1a831
Create Date: 2026-09-08 11:16:30.775856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c38ab889b22a'
down_revision: Union[str, Sequence[str], None] = 'fe098cc1a831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('remote_allowed', sa.Boolean(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('med_salary', sa.Float(), nullable=True),
    sa.Column('pay_period', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_name'), 'job_postings', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_postings_external_id'), 'job_postings', ['external_id'], unique=True)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_external_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_name'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
